-- Check Identity Columns in BLOODCONNECT Database
-- Run this script to verify that all primary key columns are properly configured as IDENTITY

USE [BLOODCONNECT]
GO

-- Check DONOR table
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    COLUMNPROPERTY(OBJECT_ID('DONOR'), COLUMN_NAME, 'IsIdentity') AS IsIdentity,
    COLUMNPROPERTY(OBJECT_ID('DONOR'), COLUMN_NAME, 'SeedValue') AS SeedValue,
    COLUMNPROPERTY(OBJECT_ID('DONOR'), COLUMN_NAME, 'IncrementValue') AS IncrementValue
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'DONOR' AND COLUMN_NAME = 'DONORID'
GO

-- Check RECEIPIENT table
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    COLUMNPROPERTY(OBJECT_ID('RECEIPIENT'), COLUMN_NAME, 'IsIdentity') AS IsIdentity,
    COLUMNPROPERTY(OBJECT_ID('RECEIPIENT'), COLUMN_NAME, 'SeedValue') AS SeedValue,
    COLUMNPROPERTY(OBJECT_ID('RECEIPIENT'), COLUMN_NAME, 'IncrementValue') AS IncrementValue
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'RECEIPIENT' AND COLUMN_NAME = 'RECEIPIENTID'
GO

-- Check BLOODREQUEST table
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    COLUMNPROPERTY(OBJECT_ID('BLOODREQUEST'), COLUMN_NAME, 'IsIdentity') AS IsIdentity,
    COLUMNPROPERTY(OBJECT_ID('BLOODREQUEST'), COLUMN_NAME, 'SeedValue') AS SeedValue,
    COLUMNPROPERTY(OBJECT_ID('BLOODREQUEST'), COLUMN_NAME, 'IncrementValue') AS IncrementValue
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'BLOODREQUEST' AND COLUMN_NAME = 'REQUESTID'
GO

-- Check BLOODINVENTORY table
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    COLUMNPROPERTY(OBJECT_ID('BLOODINVENTORY'), COLUMN_NAME, 'IsIdentity') AS IsIdentity,
    COLUMNPROPERTY(OBJECT_ID('BLOODINVENTORY'), COLUMN_NAME, 'SeedValue') AS SeedValue,
    COLUMNPROPERTY(OBJECT_ID('BLOODINVENTORY'), COLUMN_NAME, 'IncrementValue') AS IncrementValue
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'BLOODINVENTORY' AND COLUMN_NAME = 'UNITID'
GO

-- Check BLOODDONATION table
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    COLUMNPROPERTY(OBJECT_ID('BLOODDONATION'), COLUMN_NAME, 'IsIdentity') AS IsIdentity,
    COLUMNPROPERTY(OBJECT_ID('BLOODDONATION'), COLUMN_NAME, 'SeedValue') AS SeedValue,
    COLUMNPROPERTY(OBJECT_ID('BLOODDONATION'), COLUMN_NAME, 'IncrementValue') AS IncrementValue
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'BLOODDONATION' AND COLUMN_NAME = 'DONATIONID'
GO

-- Check EMAILNOTIFICATION table
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    COLUMNPROPERTY(OBJECT_ID('EMAILNOTIFICATION'), COLUMN_NAME, 'IsIdentity') AS IsIdentity,
    COLUMNPROPERTY(OBJECT_ID('EMAILNOTIFICATION'), COLUMN_NAME, 'SeedValue') AS SeedValue,
    COLUMNPROPERTY(OBJECT_ID('EMAILNOTIFICATION'), COLUMN_NAME, 'IncrementValue') AS IncrementValue
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'EMAILNOTIFICATION' AND COLUMN_NAME = 'NOTIFICATIONID'
GO

-- Summary: All IsIdentity columns should return 1 (true)
PRINT 'If any IsIdentity column shows 0 (false), the table needs to be recreated with proper IDENTITY columns.'
