-- Fix Identity Columns in BLOODCONNECT Database
-- This script will recreate tables with proper IDENTITY columns if needed

USE [BLOODCONNECT]
GO

-- Drop and recreate DONOR table with proper IDENTITY
IF EXISTS (SELECT * FROM sysobjects WHERE name='DONOR' AND xtype='U')
BEGIN
    DROP TABLE [dbo].[DONOR]
END
GO

CREATE TABLE [dbo].[DONOR](
    [DONORID] [int] IDENTITY(1,1) NOT NULL,
    [FIRSTNAME] [varchar](100) NOT NULL,
    [LASTNAME] [varchar](100) NOT NULL,
    [PHONENUMBER] [varchar](15) NOT NULL,
    [EMAILADDRESS] [varchar](100) NULL,
    [BLOODTYPE] [char](5) NOT NULL,
    [MEDICALHISTORY] [text] NOT NULL,
    [QRCODE] [varchar](300) NULL,
    CONSTRAINT [PK_DONOR] PRIMARY KEY CLUSTERED ([DONORID] ASC)
)
GO

-- Drop and recreate RECEIPIENT table with proper IDENTITY
IF EXISTS (SELECT * FROM sysobjects WHERE name='RECEIPIENT' AND xtype='U')
BEGIN
    DROP TABLE [dbo].[RECEIPIENT]
END
GO

CREATE TABLE [dbo].[RECEIPIENT](
    [RECEIPIENTID] [int] IDENTITY(1,1) NOT NULL,
    [FIRSTNAME] [varchar](100) NOT NULL,
    [LASTNAME] [varchar](100) NOT NULL,
    [EMAIL] [varchar](100) NOT NULL,
    [PHONENUMBER] [int] NULL,
    [BLOODTYPE] [varchar](5) NOT NULL,
    [QUANTITYREQUESTED] [int] NULL,
    CONSTRAINT [PK_RECEIPIENT] PRIMARY KEY CLUSTERED ([RECEIPIENTID] ASC)
)
GO

-- Drop and recreate BLOODREQUEST table with proper IDENTITY
IF EXISTS (SELECT * FROM sysobjects WHERE name='BLOODREQUEST' AND xtype='U')
BEGIN
    DROP TABLE [dbo].[BLOODREQUEST]
END
GO

CREATE TABLE [dbo].[BLOODREQUEST](
    [REQUESTID] [int] IDENTITY(1,1) NOT NULL,
    [BLOODTYPEREQUIRED] [varchar](5) NOT NULL,
    [QUANTITYREQUESTED] [int] NULL,
    [REQUESTEDDATE] [datetime] NOT NULL,
    [STATUS] [varchar](50) NOT NULL,
    [RECEIPIENTID] [int] NOT NULL,
    CONSTRAINT [PK_BLOODREQUEST] PRIMARY KEY CLUSTERED ([REQUESTID] ASC),
    CONSTRAINT [FK_BLOODREQUEST_RECEIPIENT] FOREIGN KEY([RECEIPIENTID]) REFERENCES [dbo].[RECEIPIENT] ([RECEIPIENTID])
)
GO

-- Drop and recreate BLOODINVENTORY table with proper IDENTITY
IF EXISTS (SELECT * FROM sysobjects WHERE name='BLOODINVENTORY' AND xtype='U')
BEGIN
    DROP TABLE [dbo].[BLOODINVENTORY]
END
GO

CREATE TABLE [dbo].[BLOODINVENTORY](
    [UNITID] [int] IDENTITY(1,1) NOT NULL,
    [BLOODTYPE] [varchar](5) NOT NULL,
    [QUANTITY] [int] NULL,
    [EXPIRATIONDATE] [datetime] NOT NULL,
    [STORAGELOCATION] [varchar](100) NULL,
    [STATUS] [varchar](50) NULL,
    CONSTRAINT [PK_BLOODINVENTORY] PRIMARY KEY CLUSTERED ([UNITID] ASC)
)
GO

-- Drop and recreate BLOODDONATION table with proper IDENTITY
IF EXISTS (SELECT * FROM sysobjects WHERE name='BLOODDONATION' AND xtype='U')
BEGIN
    DROP TABLE [dbo].[BLOODDONATION]
END
GO

CREATE TABLE [dbo].[BLOODDONATION](
    [DONATIONID] [int] IDENTITY(1,1) NOT NULL,
    [BLOODTYPE] [varchar](5) NOT NULL,
    [QUANTITY] [int] NOT NULL,
    [DONATIONDATE] [datetime] NULL,
    [DONORID] [int] NOT NULL,
    CONSTRAINT [PK_BLOODDONATION] PRIMARY KEY CLUSTERED ([DONATIONID] ASC),
    CONSTRAINT [FK_BLOODDONATION_DONOR] FOREIGN KEY([DONORID]) REFERENCES [dbo].[DONOR] ([DONORID])
)
GO

-- Drop and recreate EMAILNOTIFICATION table with proper IDENTITY
IF EXISTS (SELECT * FROM sysobjects WHERE name='EMAILNOTIFICATION' AND xtype='U')
BEGIN
    DROP TABLE [dbo].[EMAILNOTIFICATION]
END
GO

CREATE TABLE [dbo].[EMAILNOTIFICATION](
    [NOTIFICATIONID] [int] IDENTITY(1,1) NOT NULL,
    [SUBJECT] [varchar](100) NULL,
    [MESSAGE] [text] NULL,
    [DATESENT] [datetime] NOT NULL,
    [RECEIPIENTID] [int] NOT NULL,
    CONSTRAINT [PK_EMAILNOTIFICATION] PRIMARY KEY CLUSTERED ([NOTIFICATIONID] ASC),
    CONSTRAINT [FK_EMAILNOTIFICATION_RECEIPIENT] FOREIGN KEY([RECEIPIENTID]) REFERENCES [dbo].[RECEIPIENT] ([RECEIPIENTID])
)
GO

PRINT 'All tables have been recreated with proper IDENTITY columns.'
PRINT 'You can now test creating new records without the NULL insertion error.'
